firecrawl_api_key = "fc-5b9ec38c1f764b7c896696878063e18d"
cerebras_api_key = "csk-x35t5njhv4jrhwjy4f46x6dxj5yvm9yv8xv9dfdm9mjfkr4x"


# Additional configuration options
[config]
log_level = "INFO"
max_sites_per_query = 7
max_results_per_site = 5
