# API Keys - Replace with your actual API keys
firecrawl_api_key = "your_firecrawl_api_key_here"
cerebras_api_key = "your_cerebras_api_key_here"

# Additional configuration options
[config]
log_level = "INFO"
max_sites_per_query = 5
max_results_per_site = 3

# To use this file:
# 1. Rename it to secrets.toml
# 2. Replace placeholder values with your actual API keys
# 3. Keep this file private and never commit it to version control
