# API Keys - Replace with your actual API keys
firecrawl_api_key = "fc-5b9ec38c1f764b7c896696878063e18d"
cerebras_api_key = "csk-x35t5njhv4jrhwjy4f46x6dxj5yvm9yv8xv9dfdm9mjfkr4x"

# Additional configuration options
[config]
log_level = "INFO"
max_sites_per_query = 5
max_results_per_site = 3

# To use this file:
# 1. Rename it to secrets.toml
# 2. Replace placeholder values with your actual API keys
# 3. Keep this file private and never commit it to version control
